### ISSUE TITLE
Supporting `didUpdateAttrs`

### ISSUE THREAD

**Issue by GavinJoyce** [workmanw/ember-diff-attrs#4]
Having the addon only support `didReceiveAttrs` makes it much less valuable as it's only a partial solution to attribute change tracking and leaves consuming app having to implement their own tracking logic when they are interested in changes in `didUpdateAttrs`.

I'm interested in helping to explore how this addon might support `didUpdateAttrs` as well as the currently supported `didReceiveAttrs` (see https://github.com/emberjs/rfcs/pull/191#issuecomment-269146689 for some context).

I'm just beginning to look into it now, I'm creating this issue to track any conversation or progress.

/cc @workmanw

**Comment by GavinJoyce** [comment]
<img width="1217" alt="screen shot 2017-10-31 at 13 36 02" src="https://user-images.githubusercontent.com/2526/32226498-99fcdfa6-be40-11e7-8839-279a650fb199.png">
<img width="1203" alt="screen shot 2017-10-31 at 13 36 10" src="https://user-images.githubusercontent.com/2526/32226499-9a16896a-be40-11e7-89e9-a0ebd6224a1a.png">
<img width="1221" alt="screen shot 2017-10-31 at 13 36 45" src="https://user-images.githubusercontent.com/2526/32226500-9a2fe8ba-be40-11e7-9fd1-293c4656bc59.png">
<img width="1027" alt="screen shot 2017-10-31 at 13 36 51" src="https://user-images.githubusercontent.com/2526/32226501-9a49c6a4-be40-11e7-882d-0e81b7071393.png">

**Comment by GavinJoyce** [comment]
The mixin approach works great, here's the WIP API that I'm using:

```js
import Ember from 'ember';
import { AttrsChangeDiff } from 'ember-diff-attrs';

export default Ember.Component.extend(AttrsChangeDiff, {
 trackChangeAttrs: ['email', 'isAdmin'], //TODO: support advanced config too
 
 didChangeAttrs(changes) {
   if(changes.email) {
     console.log('email previous', changes.email.previous);
     console.log('email current', changes.email.current);
   }
 }
});
```

**Comment by GavinJoyce** [comment]
WIP PR here: https://github.com/workmanw/ember-diff-attrs/pull/5

**Comment by GavinJoyce** [comment]
For comparison:

Current API:

```js
import diffAttrs from 'ember-diff-attrs';

export default Ember.Component.extend({
  didReceiveAttrs: diffAttrs('email', 'isAdmin', function(changedAttrs, ...args) {
    this._super(...args);

    if(changedAttrs && changedAttrs.email) {
      let oldEmail = changedAttrs.email[0],
          newEmail = changedAttrs.email[1];
      // Do stuff
    }
  })
});
```

New API:

```js
import DidChangeAttrs from 'ember-did-change-attrs';

export default Ember.Component.extend(DidChangeAttrs, {
 didChangeAttrsConfig: {
   attrs: ['email', 'isAdmin']
 },
 
 didChangeAttrs(changes) {
   if(changes.email) {
     let oldEmail = changes.email.previous,
         newEmail = changes.email.current;
     // Do stuff
   }
 }
});
```

**Comment by GavinJoyce** [comment]
@workmanw, a couple of possibly controversial thoughts:

 * we should retire the `diffAttrs` API in favour of the Mixin approach
 * we should rename this addon to `ember-did-change-attrs`

**Comment by workmanw** [comment]
@GavinJoyce I'd like to know if anyone else (who might be lurking 👀) would feel about that. 

I understand the goal of that change would be to only have one way to do use it. I'm a little hesitant to go whole-hog and do away with the decorator approach because I genuinely think there are a lot of people against Mixins. Again, I'm not one of them, had I just written this for myself (and not as an Addon) I would have reached for a Mixin solution. 

Maybe the best option would be for us to create a new addon `ember-did-change-attrs` with this approach, and cross link the README.mds. That would be non controversial and make it easy for us to track adoption. I have some free cycles right now, I could bootstrap the addon and add you to it as a committer if you'd like.

Thoughts?

**Comment by GavinJoyce** [comment]
> Maybe the best option would be for us to create a new addon ember-did-change-attrs with this approach, and cross link the README.mds. 

Sounds like a good approach to me, thanks

**Comment by workmanw** [comment]
@GavinJoyce I'm on it. Hold tight.

**Comment by workmanw** [comment]
@GavinJoyce et al, done! [ember-did-change-attrs](https://github.com/workmanw/ember-did-change-attrs) is now a bootstrapped addon. I'm happy to continue collaborating over there. I'll open an issue and cross link it.
